### ISSUE TITLE
Error: EACCES, mkdir '/home/developer/.npm/cssnano/2.6.1'

### ISSUE THREAD

**Issue by tnedich** [alexfedoseev/generator-flux-on-rails#2]
Getting this error when running generator. App part is generated but API part is not.

`sudo yo flux-on-rails my-blog`

**OS: Ubuntu 14.04**

npm ERR! Error: EACCES, mkdir '/home/developer/.npm/cssnano/2.6.1'
npm ERR!  { [Error: EACCES, mkdir '/home/developer/.npm/cssnano/2.6.1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/developer/.npm/cssnano/2.6.1',
npm ERR!   parent: 'css-loader' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "autoprefixer-loader" "babel-eslint" "babel-loader" "chunk-manifest-webpack-plugin" "compression-webpack-plugin" "css-loader" "del" "eslint" "eslint-plugin-babel" "eslint-plugin-react" "extract-text-webpack-plugin" "gulp" "gulp-changed" "gulp-if" "gulp-imagemin" "gulp-util" "node-notifier" "react-hot-loader" "redux-devtools" "run-sequence" "style-loader" "stylus-loader" "webpack" "webpack-dev-server" "webpack-manifest-plugin" "chai" "jsdom" "mocha" "sinon" "--save-dev" "--loglevel" "error"
npm ERR! cwd /home/developer/Desktop/RAILS/my-blog/my-blog-app
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /home/developer/.npm/cssnano/2.6.1
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/developer/.npm/cssnano/2.6.1'
npm ERR! not ok code 0
Completed.

$ npm shrinkwrap --loglevel error
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: eslint-plugin-babel@2.1.1 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/eslint-plugin-babel
npm ERR! extraneous: eslint-plugin-react@3.2.3 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/eslint-plugin-react
npm ERR! extraneous: compression-webpack-plugin@0.2.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/compression-webpack-plugin
npm ERR! extraneous: webpack-manifest-plugin@0.4.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/webpack-manifest-plugin
npm ERR! extraneous: babel-loader@5.3.2 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/babel-loader
npm ERR! extraneous: chai@3.2.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/chai
npm ERR! extraneous: extract-text-webpack-plugin@0.8.2 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/extract-text-webpack-plugin
npm ERR! extraneous: redux-devtools@1.1.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/redux-devtools
npm ERR! extraneous: sinon@1.16.1 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/sinon
npm ERR! extraneous: style-loader@0.12.3 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/style-loader
npm ERR! extraneous: autoprefixer-loader@2.0.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/autoprefixer-loader
npm ERR! extraneous: chunk-manifest-webpack-plugin@0.0.1 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/chunk-manifest-webpack-plugin
npm ERR! extraneous: gulp-changed@1.3.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/gulp-changed
npm ERR! extraneous: mocha@2.2.5 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/mocha
npm ERR! extraneous: run-sequence@1.1.2 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/run-sequence
npm ERR! extraneous: babel-eslint@4.0.10 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/babel-eslint
npm ERR! extraneous: gulp-if@1.2.5 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/gulp-if
npm ERR! extraneous: stylus-loader@1.2.1 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/stylus-loader
npm ERR! extraneous: jsdom@6.1.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/jsdom
npm ERR! extraneous: node-notifier@4.2.3 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/node-notifier
npm ERR! extraneous: webpack-dev-server@1.10.1 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/webpack-dev-server
npm ERR! extraneous: del@1.2.1 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/del
npm ERR! extraneous: gulp@3.9.0 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/gulp
npm ERR! extraneous: gulp-util@3.0.6 /home/developer/Desktop/RAILS/my-blog/my-blog-app/node_modules/gulp-util
npm ERR!     at shrinkwrap_ (/usr/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
npm ERR!     at /usr/lib/node_modules/npm/lib/shrinkwrap.js:24:5
npm ERR!     at /usr/lib/node_modules/npm/lib/ls.js:45:30
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.16.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "shrinkwrap" "--loglevel" "error"
npm ERR! cwd /home/developer/Desktop/RAILS/my-blog/my-blog-app
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/developer/Desktop/RAILS/my-blog/my-blog-app/npm-debug.log
npm ERR! not ok code 0
Completed.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, no such file or directory '/home/developer/Desktop/RAILS/my-blog/my-blog-api/Gemfile'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at readFileAsString (/usr/lib/node_modules/generator-flux-on-rails/node_modules/yeoman-generator/lib/actions/wiring.js:277:13)
    at api.editGemfile (/usr/lib/node_modules/generator-flux-on-rails/app/index.js:370:64)
    at module.exports.yeoman.generators.Base.extend.writing.scaffoldApi (/usr/lib/node_modules/generator-flux-on-rails/app/index.js:509:16)
    at /usr/lib/node_modules/generator-flux-on-rails/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback](timers.js:363:15)

**Comment by andresgutgon** [comment]
> Please try running this command again as root/Administrator.

Do you have permissions to write in the folder where you're trying to run this generator?

**Comment by tnedich** [comment]
I am running generator like this: 

`sudo yo flux-on-rails my-blog`

**Comment by alex35mil** [comment]
+1 to question above. `EACCES` means something wrong with permissions.

**Comment by alex35mil** [comment]
It seems you don't have permissions to run `npm` commands without sudo.
Please try to `npm install some-module` without `sudo` and post here results.

**Comment by tnedich** [comment]
Something is wrong with my machine. My bad. Sorry. I cannot install anything without sudo.

npm ERR! Error: EACCES, mkdir '/home/developer/.npm/rsvp/3.0.21'
npm ERR!  { [Error: EACCES, mkdir '/home/developer/.npm/rsvp/3.0.21']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/developer/.npm/rsvp/3.0.21',
npm ERR!   parent: 'traceur' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "traceur"
npm ERR! cwd /home/developer/Desktop/RAILS
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /home/developer/.npm/rsvp/3.0.21
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/developer/.npm/rsvp/3.0.21'
npm ERR! not ok code 0

**Comment by alex35mil** [comment]
No problems, closing it.
